### PR TITLE
Apple design

### PR DESCRIPTION
**Pull request by damiecode**

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
Hi, you did a great Job :clap: There are just few things to do, and you will be good to go. :smile:
* Please, ensure there are stickler checks on your project with a passed check, currently there are no checks on your project.
* In your **bottom class**, your images should link to another address, in this case ``` # ``` 
* Finally, the images on your bottom class does not fit into the full width of your screen. Here it is 

#### Your design on full screen

Screenshot from 2019-08-25 19-59-07


#### On apple.com

Screenshot from 2019-08-25 20-19-04

#### Implement these changes, and submit another code review

**Comment by damiecode** [comment]
Thanks. Please I am actually having issue with the stickler. I did the necessary things but I'm not getting any checks. I'm hoping you could help me figure out what's wrong. Thank you

**Comment by uche-inyama** [comment]
#### Did you activate your project on [stickler](https://stickler-ci.com/). if not, activate it. :thinking: 
Please, submit another review form when everything is done. :smile:

**Comment by damiecode** [comment]
I have done that but let me start the whole process again

**Pull request closed without merging**
